kind: Service
apiVersion: v1
metadata:
  name: es-service
  namespace: elastic
  labels:
    app: es
spec:
  type: NodePort
  selector:
    app: es
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node 

